### ISSUE TITLE
Can not build with PostgreSQL 13

### ISSUE THREAD

**Issue by yugo-n** [sraoss/pg_ivm#9]
```
$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I. -I./ -I/usr/local/src/pgsql/current-13/include/server -I/usr/local/src/pgsql/current-13/include/internal  -D_GNU_SOURCE   -c -o pg_ivm.o pg_ivm.c
pg_ivm.c: In function 'create_immv':
pg_ivm.c:188:8: error: 'CreateTableAsStmt' {aka 'struct CreateTableAsStmt'} has no member named 'objtype'; did you mean 'type'?
  188 |  ctas->objtype = OBJECT_MATVIEW;
      |        ^~~~~~~
      |        type
```

**Comment by MichaelDBA** [comment]
I totally disagree with @Bessonov !  Thanks for your efforts to make it compatible with non-EOL versions of Postgres.

**Comment by Bessonov** [comment]
@MichaelDBA 

> I totally disagree with @Bessonov !

Because...
- You don't want update your DB, even you must do it sooner or later?
- You don't want spend your time and contribute it by yourself?
- You don't want hire someone to do it for you?
- You will slow down development of this feature?
- You want more complex code base because of supporting different versions?
- You want that the team do more testing because of older versions?
- You want that the team spends more time to support older versions after GA?

Did you ask PG team to backport PG14 features to PG13 just because you need them? No? TBH, I can't understand people like you. Why do you want hold down the development? Does oracle pay you? I'm more interested that this feature get done (eg. https://github.com/sraoss/pg_ivm/issues/4 ) instead of spending time for outdated versions.

I'm on PG13 too, but it's totally reasonable updating the database to get new features. And if the team decides ship it in PG15, because they can use new functions from PG15 and spend less time on development, I would strongly agree with this decision. I value the time of developers and I care very much about it.

Anyway, there is a PR for that now. But the time spend on this isn't available for development of this feature anymore and will slow down the development further.

**Comment by yugo-n** [comment]
Actually, we would not like to support too old versions as Bessonov said, but, on the other hand, we think we also would like many pepole to use pg_ivm and give us feedback. So, we decided to support PG13 since we've recognized that it is easy thanks to the PR, and I've already merged it. pg_ivm is supported from feedback from you all. Thank!
